name: Playwright Tests (learning)

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Login Username'
        required: true
        default: 'student'
      password:
        description: 'Login Password'
        required: true
        default: 'Password123'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:                 
          LOGIN_USERNAME: ${{ github.event.inputs.username }}
          LOGIN_PASSWORD: ${{ github.event.inputs.password }}
        run: npx playwright test barat/learning.spec.js --project=chromium